# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('total_round', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('round', models.IntegerField(default=0)),
                ('weather', models.CharField(max_length=20, null=True)),
                ('crowd', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('strong_side', models.CharField(default='', max_length=50)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.BooleanField()),
                ('enter_minute', models.IntegerField(null=True)),
                ('exit_minute', models.IntegerField(null=True)),
                ('yellow_cards', models.IntegerField(null=True)),
                ('red_cards', models.IntegerField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('passes', models.IntegerField(null=True)),
                ('shots', models.IntegerField(null=True)),
                ('shots_on_target', models.IntegerField(null=True)),
                ('touches', models.IntegerField(null=True)),
                ('fouls', models.IntegerField(null=True)),
                ('penalties', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='soccerapp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_title', models.CharField(default='', max_length=200, null=True)),
                ('position_group', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_size', models.IntegerField(null=True)),
                ('construction_year', models.DateField(null=True)),
                ('cords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='soccerapp.Cords')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_final', models.IntegerField()),
                ('goals_half', models.IntegerField()),
                ('formation', models.CharField(max_length=10, null=True)),
                ('corners', models.IntegerField(null=True)),
                ('fouls_commited', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='soccerapp.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='soccerapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('buy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_transactions', to='soccerapp.Team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.Player')),
                ('sell_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to='soccerapp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playermatch',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccerapp.Position'),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='soccerapp.TeamMatch'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soccerapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='soccerapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='soccerapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='soccerapp.League'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='soccerapp.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='soccerapp.Stadium'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('nami', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='teammatch',
            unique_together=set([('team', 'match')]),
        ),
        migrations.AlterUniqueTogether(
            name='playermatch',
            unique_together=set([('player', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('league', 'home_team', 'away_team', 'match_date')]),
        ),
    ]
