# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccerapp', '0004_externaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldata',
            name='data',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
